[package]
name = "cucumber_rust"
version = "0.7.3"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "Cucumber testing framework for Rust, with async support. Fully native, no external test runners or dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cucumber", "testing", "bdd", "atdd", "async"]
categories = ["asynchronous", "development-tools::testing"]
repository = "https://github.com/bbqsrc/cucumber-rust"
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
edition = "2018"

[dependencies]
gherkin = { package = "gherkin_rust", version = "0.8.3" }

async-stream = "0.3.0"
async-trait = "0.1.40"
cute_custom_default = "2.1.0"
futures = "0.3.5"
futures-timer = "3.0.2"
globwalk = "0.8.0"
regex = "1.3.9"
shh = "1.0.1"
thiserror = "1.0.20"
termcolor = "1.1.0"
textwrap = { version = "0.12.1", features = ["terminal_size"] }
pathdiff = "0.2.0"
clap = "2.33"

[[test]]
name = "cucumber_builder"
harness = false

[[test]]
name = "integration_test"
harness = true
edition = "2018"

[dev-dependencies]
capture-runner = { path = "tests/fixtures/capture-runner" }
serial_test = "0.5.0"

[workspace]
members = ["tests/fixtures/capture-runner"]
default-members = ["."]

